### PR TITLE
Use multierr instead of VerificationResult

### LINKED ISSUE #184: Use `multierr` instead of `VerificationResult`
We could combine errors from different verification steps with [multierr](https://pkg.go.dev/go.uber.org/multierr#section-readme) instead of our home-cooked `VerificationResult`.

Downside: We can't distinguish between a verification step that failed because the verification failed (e.g., the provenance has an empty build cmd), and a failure in the process of verification.

However, the failure in the process are all due to `ProvenanceIR` having the wrong shape, which should go away after adding the changes discussed in #166 and #165 .

### PR DESCRIPTION
**Pull request by mariaschett**
Fixes #184 .

- [x] Tests pass

### CODE REVIEW

File: internal/verifier/verifier_test.go [hunk 1]
```diff
@@ -115,12 +107,10 @@ func TestVerifyHasNoValues(t *testing.T) {
 	}
 
 	// We don't expect any verification to happen.
-	result, err := verifier.Verify()
+	err := verifier.Verify()
```
Comment (rbehjati) [inline internal/verifier/verifier_test.go:110]: Can this be changed into `if err := ...; err != nil {...}`?

**Review by rbehjati — APPROVED** [review]
This is great. Thanks :)

File: internal/verifier/verifier_test.go (hunk 1 above)
Comment (mariaschett) [reply internal/verifier/verifier_test.go]: Done.
